### ISSUE TITLE
servername?

### ISSUE THREAD

**Issue by Homer-Sim** [jazzdd86/phpVirtualbox#5]
Hello I have some issues finding all relevant informations to run this container.
 
docker run --name vbox_http --restart=always \                  ====>clear
    -p 8880:80 \                                                                    ====>clear
    -e ID_PORT_18083_TCP=192.168.100.10:18083 \           ====>IP is from my server where VB is running:port is a guess
    -e ID_NAME=srv-docker \                  ====>this is name ob ubuntuserver running VB??!!
    -e ID_USER=vboxUser \                  ====>this is the user created for vB
    -e ID_PW='pass' \                  ====>should be clear
    -e CONF_browserRestrictFolders="/data,/home" \                  ====>no idea if this is needed
    -d jazzdd/phpvirtualbox

Maybe you can give me alittle support

I want to use this continer to set uo my VMs ....
Thanks

**Comment by jazzdd86** [comment]
Sorry for this delay, I hope you found the correct parameters for your setup. Otherwise I will answer your questions now.
-e ID_PORT_18083_TCP --> yes this is the IP of the PC running the vboxwebsrv service, default port is normally 18083

-e ID_NAME=srv-docke --> this is a free name to identify your virtualbox host machine (you can have more than one machine with virtualbox on it and use it through one web interface)

-e ID_USER=vboxUser - user running the vboxwebsrv 

-e CONF_browserRestrictFolders="/data,/home" --> used to restrict folders for your webinterface, you dont need to use it
